version: "0.2"
ignorePaths:
  - archive
  - dist
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - aigc
  - aistudio
  - baichuan
  - chatcompletion
  - embo
  - erniebot
  - hunyuan
  - inpaint
  - inpainted
  - jiti
  - lineart
  - longcontext
  - openai
  - openpose
  - permissioning
  - qwen
  - qwenai
  - sdxl
  - trivago
  - vyro
  - wanx
  - wechat
  - wechaty
  - Weightage
  - yiyan
ignoreWords:
  - zhengxs
