version: "0.2"
ignorePaths:
  - archive
  - dist
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - aistudio
  - baichuan
  - chatcompletion
  - claudeai
  - deepl
  - dingtalk
  - embo
  - erniebot
  - GPTAPI
  - hotlist
  - hunyuan
  - inpaint
  - inpainted
  - jiti
  - keyv
  - langchain
  - languagedetect
  - lineart
  - llmapi
  - llms
  - longcontext
  - moyu
  - msgtype
  - openai
  - openpose
  - preinstall
  - qianfan
  - qwen
  - qwenai
  - sdxl
  - tiktoken
  - trivago
  - vuepress
  - vyro
  - wechat
  - wechaty
  - Weightage
  - yiyan
  - yiyian
ignoreWords:
  - zhengxs
